// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/elements/:guid': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/elements/[guid].put').default>>>>
    }
    '/api/elements/sync': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/elements/sync.post').default>>>>
    }
    '/api/items/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/[id].put').default>>>>
    }
    '/api/items/clear': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/clear.delete').default>>>>
    }
    '/api/items': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/items/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}